/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 24 02:58:59 GMT 2018
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.Year;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CalendarUnit_ESTest extends CalendarUnit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Year year0 = new Year(465);
      year0.setCurrentPos(0);
      int int0 = year0.getCurrentPos();
      assertEquals(0, year0.getYear());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Year year0 = new Year(4544);
      int int0 = year0.getCurrentPos();
      assertEquals(4544, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Year year0 = new Year((-2938));
      int int0 = year0.getCurrentPos();
      assertEquals((-2938), int0);
  }
}
