/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 25 04:09:59 GMT 2018
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import net.mooctest.InsertionResult;
import net.mooctest.InternalNode;
import net.mooctest.LeafNode;
import net.mooctest.Node;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InternalNode_ESTest extends InternalNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer(309);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(309);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(309, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode1, leafNode1);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(309, insertionResult0);
      internalNode0.insert(309, insertionResult0);
      assertEquals(1, internalNode0.getNodeSize());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(2);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(2);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(2, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode1, leafNode1);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(2, insertionResult0);
      internalNode0.t = (-1437);
      // Undeclared exception!
      try { 
        internalNode0.insert(2, insertionResult0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1438
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer(7);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(7);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(1555, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode1, leafNode1);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(7, insertionResult0);
      internalNode0.insert(1555, insertionResult0);
      int int0 = internalNode0.order(1555);
      assertEquals(1, internalNode0.getNodeSize());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Integer integer0 = new Integer(7);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(7);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(1536, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(7);
      InsertionResult<Object> insertionResult1 = new InsertionResult<Object>(integer0, leafNode0, leafNode1, insertionResult0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(7, insertionResult1);
      Object object0 = new Object();
      internalNode0.insert(10, object0);
      internalNode0.insert(1536, insertionResult1);
      int int0 = internalNode0.order(1536);
      assertEquals(2, internalNode0.getNodeSize());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Integer integer0 = new Integer(10);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(10);
      InsertionResult<Object> insertionResult0 = leafNode0.insert(10, "rw_Ay0]%|");
      leafNode0.insert(1508, leafNode0);
      InsertionResult<Object> insertionResult1 = new InsertionResult<Object>(integer0, leafNode0, leafNode0, insertionResult0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(10, insertionResult1);
      int int0 = internalNode0.order(1508);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer(Integer.MAX_VALUE);
      InternalNode<LeafNode<String>> internalNode0 = new InternalNode<LeafNode<String>>(2);
      InsertionResult<LeafNode<String>> insertionResult0 = new InsertionResult<LeafNode<String>>(integer0, internalNode0, internalNode0);
      InternalNode<LeafNode<String>> internalNode1 = new InternalNode<LeafNode<String>>(2, insertionResult0);
      // Undeclared exception!
      try { 
        internalNode1.order(1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer(1991);
      LeafNode<String> leafNode0 = new LeafNode<String>(1991);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>(integer0, leafNode0, leafNode0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1991, insertionResult0);
      internalNode0.insert(Integer.MAX_VALUE, "r&m");
      internalNode0.insert((-1), "net.mooctest.LeafNode@0000000001#net.mooctest.LeafNode@0000000001");
      assertEquals(2, internalNode0.getNodeSize());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Integer integer0 = new Integer(1991);
      LeafNode<String> leafNode0 = new LeafNode<String>(1991);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>(integer0, leafNode0, leafNode0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1991, insertionResult0);
      internalNode0.insert(Integer.MAX_VALUE, "r&m");
      int int0 = internalNode0.getNodeSize();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(10);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(10);
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode0, leafNode0);
      leafNode0.insert(1520, leafNode0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(10, insertionResult0);
      internalNode0.getMaxChildNode();
      assertEquals(2, internalNode0.getNodeSize());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Integer integer0 = new Integer(1991);
      LeafNode<String> leafNode0 = new LeafNode<String>(1991);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>(integer0, leafNode0, leafNode0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1991, insertionResult0);
      leafNode0.insert(2, "{{LKc`E=7nF^");
      Node<String> node0 = internalNode0.getChildNode(0);
      assertEquals(1, node0.getNodeSize());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      InternalNode<String> internalNode0 = new InternalNode<String>(1);
      List<Integer> list0 = internalNode0.keys;
      LinkedList<Node<InternalNode<Object>>> linkedList0 = new LinkedList<Node<InternalNode<Object>>>();
      InternalNode<InternalNode<Object>> internalNode1 = new InternalNode<InternalNode<Object>>(3501, list0, linkedList0);
      // Undeclared exception!
      try { 
        internalNode1.toString();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LeafNode<String> leafNode0 = new LeafNode<String>(1070);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>((Integer) null, leafNode0, leafNode0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1070, insertionResult0);
      // Undeclared exception!
      try { 
        internalNode0.order(1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.InternalNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer(2);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(2);
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode0, leafNode0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(2, insertionResult0);
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      internalNode0.keys = (List<Integer>) linkedList0;
      // Undeclared exception!
      try { 
        internalNode0.order(1508);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(1);
      LeafNode<String> leafNode0 = new LeafNode<String>(929);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>((-1));
      InsertionResult<String> insertionResult1 = new InsertionResult<String>(integer0, leafNode0, leafNode0, insertionResult0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1, insertionResult1);
      List<Integer> list0 = internalNode0.keys;
      LinkedList<Node<Integer>> linkedList0 = new LinkedList<Node<Integer>>();
      InternalNode<Integer> internalNode1 = new InternalNode<Integer>(1, list0, linkedList0);
      // Undeclared exception!
      try { 
        internalNode1.insert(2, integer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = new Integer(1991);
      InternalNode<Integer> internalNode0 = new InternalNode<Integer>(2051);
      // Undeclared exception!
      try { 
        internalNode0.insert(1991, integer0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      InternalNode<Object> internalNode0 = new InternalNode<Object>(3167);
      // Undeclared exception!
      try { 
        internalNode0.getMaxChildNode();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      LinkedList<Node<String>> linkedList1 = new LinkedList<Node<String>>();
      linkedList0.add((Integer) null);
      InternalNode<String> internalNode0 = new InternalNode<String>(488, linkedList0, linkedList1);
      // Undeclared exception!
      try { 
        internalNode0.getChildNode((-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.Node", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer(0);
      linkedList0.push(integer0);
      LinkedList<Node<Object>> linkedList1 = new LinkedList<Node<Object>>();
      InternalNode<Object> internalNode0 = new InternalNode<Object>(2839, linkedList0, linkedList1);
      // Undeclared exception!
      try { 
        internalNode0.getChildNode(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      InternalNode<String> internalNode0 = new InternalNode<String>(1502);
      // Undeclared exception!
      try { 
        internalNode0.getChildNode((-2551));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      InsertionResult<InternalNode<Integer>> insertionResult0 = new InsertionResult<InternalNode<Integer>>(0);
      InternalNode<InternalNode<Integer>> internalNode0 = null;
      try {
        internalNode0 = new InternalNode<InternalNode<Integer>>(2, insertionResult0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.InternalNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      InsertionResult<InternalNode<String>> insertionResult0 = new InsertionResult<InternalNode<String>>((-1314));
      InternalNode<InternalNode<String>> internalNode0 = null;
      try {
        internalNode0 = new InternalNode<InternalNode<String>>((-1314), insertionResult0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1315
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedList<Node<Object>> linkedList0 = new LinkedList<Node<Object>>();
      InternalNode<Object> internalNode0 = null;
      try {
        internalNode0 = new InternalNode<Object>(150, (List<Integer>) null, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      InternalNode<String> internalNode0 = null;
      try {
        internalNode0 = new InternalNode<String>(0, (List<Integer>) null, (List<Node<String>>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      InternalNode<LeafNode<Object>> internalNode0 = null;
      try {
        internalNode0 = new InternalNode<LeafNode<Object>>(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      InternalNode<String> internalNode0 = new InternalNode<String>(1);
      List<Integer> list0 = internalNode0.keys;
      LinkedList<Node<String>> linkedList0 = new LinkedList<Node<String>>();
      linkedList0.add((Node<String>) internalNode0);
      InternalNode<String> internalNode1 = new InternalNode<String>(1, list0, linkedList0);
      assertEquals(0, internalNode1.getNodeSize());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      InternalNode<Object> internalNode0 = new InternalNode<Object>(3167);
      int int0 = internalNode0.getNodeSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Integer integer0 = new Integer(1991);
      LeafNode<String> leafNode0 = new LeafNode<String>(1991);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>(integer0, leafNode0, leafNode0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1991, insertionResult0);
      Node<String> node0 = internalNode0.getChildNode(0);
      assertEquals(0, node0.getNodeSize());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Integer integer0 = new Integer(1991);
      LeafNode<String> leafNode0 = new LeafNode<String>(1991);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>(integer0, leafNode0, leafNode0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1991, insertionResult0);
      String string0 = internalNode0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Integer integer0 = new Integer(2);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(2);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(2, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode1, leafNode1);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(2, insertionResult0);
      InsertionResult<Object> insertionResult1 = internalNode0.insert(2, insertionResult0);
      assertEquals(0, internalNode0.getNodeSize());
      assertEquals(2, (int)insertionResult1.getSplitRootKey());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Integer integer0 = new Integer(1991);
      LeafNode<String> leafNode0 = new LeafNode<String>(1991);
      InsertionResult<String> insertionResult0 = new InsertionResult<String>(integer0, leafNode0, leafNode0);
      InternalNode<String> internalNode0 = new InternalNode<String>(1991, insertionResult0);
      internalNode0.insert(Integer.MAX_VALUE, "");
      // Undeclared exception!
      try { 
        internalNode0.insert(Integer.MAX_VALUE, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.mooctest.InternalNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Integer integer0 = new Integer(10);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(10);
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode0, leafNode0);
      leafNode0.insert(1520, leafNode0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(10, insertionResult0);
      int int0 = internalNode0.order(1520);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Integer integer0 = new Integer(10);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(10);
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode0, leafNode0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(10, insertionResult0);
      int int0 = internalNode0.order(1520);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Integer integer0 = new Integer(7);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(7);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(1536, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(7);
      InsertionResult<Object> insertionResult1 = new InsertionResult<Object>(integer0, leafNode0, leafNode1, insertionResult0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(7, insertionResult1);
      internalNode0.insert(1536, insertionResult1);
      int int0 = internalNode0.order(1536);
      assertEquals(1, internalNode0.getNodeSize());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Integer integer0 = new Integer(2);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(2);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(2, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode1, leafNode1);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(2, insertionResult0);
      internalNode0.t = 1;
      InsertionResult<Object> insertionResult1 = internalNode0.insert(2, insertionResult0);
      assertEquals(2, (int)insertionResult1.getSplitRootKey());
      assertEquals(0, internalNode0.getNodeSize());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Integer integer0 = new Integer(2);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(1555);
      LeafNode<Object> leafNode1 = new LeafNode<Object>(1555, leafNode0);
      leafNode1.t = 1;
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode1, leafNode1);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(2, insertionResult0);
      InsertionResult<Object> insertionResult1 = internalNode0.insert(1555, insertionResult0);
      assertEquals(0, internalNode0.getNodeSize());
      assertEquals(2, (int)insertionResult1.getSplitRootKey());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Integer integer0 = new Integer(10);
      LeafNode<Object> leafNode0 = new LeafNode<Object>(10);
      InsertionResult<Object> insertionResult0 = new InsertionResult<Object>(integer0, leafNode0, leafNode0);
      InternalNode<Object> internalNode0 = new InternalNode<Object>(10, insertionResult0);
      Node<Object> node0 = internalNode0.getMaxChildNode();
      assertEquals(0, node0.getNodeSize());
  }
}
