/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 24 02:57:54 GMT 2018
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import net.mooctest.Day;
import net.mooctest.Month;
import net.mooctest.Year;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Day_ESTest extends Day_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Year year0 = new Year((-632));
      Month month0 = new Month(1, year0);
      Day day0 = new Day(1, month0);
      Day day1 = new Day(1, month0);
      day0.increment();
      boolean boolean0 = day0.equals(day1);
      assertEquals(2, day0.getDay());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Year year0 = new Year(11);
      Month month0 = new Month(11, year0);
      Day day0 = new Day(30, month0);
      month0.increment();
      boolean boolean0 = day0.increment();
      assertEquals(31, day0.getDay());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Year year0 = new Year(3);
      Month month0 = new Month(3, year0);
      Day day0 = new Day(3, month0);
      day0.setCurrentPos(0);
      int int0 = day0.getDay();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Year year0 = new Year(7);
      Month month0 = new Month(7, year0);
      Day day0 = new Day(7, month0);
      day0.currentPos = (-537);
      int int0 = day0.getDay();
      assertEquals((-537), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Year year0 = new Year((-632));
      Month month0 = new Month(1, year0);
      Day day0 = new Day(1, month0);
      month0.currentPos = 29;
      // Undeclared exception!
      try { 
        day0.increment();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 28
         //
         verifyException("net.mooctest.Month", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Year year0 = new Year(1);
      Month month0 = new Month(1, year0);
      Day day0 = new Day(1, month0);
      boolean boolean0 = day0.isValid();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Year year0 = new Year(1);
      Month month0 = new Month(1, year0);
      Day day0 = new Day(1, month0);
      day0.currentPos = 0;
      boolean boolean0 = day0.isValid();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Year year0 = new Year(1);
      Month month0 = new Month(1, year0);
      Day day0 = new Day(1, month0);
      day0.setDay(1, month0);
      assertEquals(1, day0.getDay());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Year year0 = new Year(11);
      Month month0 = new Month(11, year0);
      Day day0 = new Day(30, month0);
      Month month1 = new Month(1, year0);
      Day day1 = new Day(30, month1);
      boolean boolean0 = day0.equals(day1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Year year0 = new Year((-627));
      Month month0 = new Month(12, year0);
      Day day0 = new Day(12, month0);
      Day day1 = new Day(12, month0);
      day1.increment();
      boolean boolean0 = day0.equals(day1);
      assertEquals(13, day1.getDay());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Year year0 = new Year((-627));
      Month month0 = new Month(12, year0);
      Day day0 = new Day(12, month0);
      boolean boolean0 = day0.equals(day0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Year year0 = new Year((-627));
      Month month0 = new Month(12, year0);
      Day day0 = new Day(12, month0);
      boolean boolean0 = day0.equals(year0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Year year0 = new Year(1);
      Month month0 = new Month(1, year0);
      Day day0 = new Day(1, month0);
      day0.setCurrentPos(1641);
      boolean boolean0 = day0.isValid();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Year year0 = new Year(1);
      Month month0 = new Month(1, year0);
      Day day0 = new Day(1, month0);
      month0.setCurrentPos((-987));
      boolean boolean0 = day0.isValid();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Day day0 = null;
      try {
        day0 = new Day((-3969), (Month) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not a valid day
         //
         verifyException("net.mooctest.Day", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Year year0 = new Year((-627));
      Month month0 = new Month(12, year0);
      Day day0 = new Day(12, month0);
      // Undeclared exception!
      try { 
        day0.setDay((-627), month0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not a valid day
         //
         verifyException("net.mooctest.Day", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Year year0 = new Year(11);
      Month month0 = new Month(11, year0);
      Day day0 = new Day(30, month0);
      boolean boolean0 = day0.increment();
      assertEquals(31, day0.getDay());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Year year0 = new Year(10);
      Month month0 = new Month(10, year0);
      Day day0 = new Day(10, month0);
      int int0 = day0.getDay();
      assertEquals(10, int0);
  }
}
