/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 25 04:23:02 GMT 2018
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.my;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class my_ESTest extends my_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      my.main();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      my my0 = new my();
  }
}
