/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 24 09:58:05 GMT 2018
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.SuffixArray;
import org.junit.runner.RunWith;

public class SuffixArray_ESTest{

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SuffixArray.computeLCP("k", "eU");
      SuffixArray.computeLCP("k", "k");
      int[] intArray0 = new int[4];
      intArray0[0] = 0;
      intArray0[0] = 0;
      intArray0[2] = 1;
      intArray0[1] = 1;
      SuffixArray.createSuffixArray("eU", intArray0, intArray0);
      SuffixArray.isSorted(intArray0, intArray0, 0);
      SuffixArray.printV(intArray0, "k");
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray(intArray0, intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SuffixArray.computeLCP("", "");
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = 0;
      String string0 = "vpvU_rJ";
      SuffixArray.printV(intArray0, "vpvU_rJ");
      int int0 = (-1);
      int int1 = (-694);
      // Undeclared exception!
      try { 
        SuffixArray.makeSuffixArray(intArray0, intArray0, (-1), (-694));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = 0;
      intArray0[1] = 2252;
      intArray0[2] = 0;
      intArray0[3] = 1572;
      intArray0[4] = 763;
      intArray0[5] = 0;
      intArray0[6] = (-1);
      int[] intArray1 = new int[0];
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("fBFcn*qh0pv}bc#>UAL", intArray0, intArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = null;
      int[] intArray1 = new int[2];
      intArray1[0] = 3;
      intArray1[1] = (-2867);
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("nN6q+%Dr8MWI++'>2", (int[]) null, intArray1);
//        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[0] = (-1);
      int int0 = (-743);
      intArray0[1] = (-743);
      intArray0[2] = 718;
      intArray0[3] = 14;
      intArray0[4] = 1849;
      SuffixArray.isSorted(intArray0, intArray0, 0);
      // Undeclared exception!
      try { 
        SuffixArray.makeSuffixArray((int[]) null, intArray0, 1849, 718);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = 0;
      int int0 = 0;
      intArray0[1] = 0;
      int int1 = (-400);
      intArray0[2] = (-400);
      int int2 = 1;
      intArray0[3] = 1;
      int int3 = 0;
      intArray0[4] = 0;
      intArray0[5] = 1728;
      intArray0[6] = 0;
      int[] intArray1 = new int[0];
      SuffixArray.makeLCPArray(intArray0, intArray1, intArray0);
      SuffixArray.printV(intArray1, "wN");
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray(intArray1, intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray0 = new int[4];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = (-2457);
      intArray0[3] = (-2657);
      SuffixArray.printV(intArray0, "%QB,Szn4i");
      SuffixArray.computeLCP("net.mooctest.SuffixArray", "");
      SuffixArray.computeLCP("<@f;mxY/. 7Y(!0TGk", "9tfjzy9>7C.gvN$<");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = null;
      int int0 = 256;
      // Undeclared exception!
      try { 
        SuffixArray.isSorted((int[]) null, (int[]) null, 256);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = "UJF%aU4a6.i^";
      int[] intArray0 = new int[9];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = (-1617);
      intArray0[3] = 0;
      intArray0[4] = (-2296);
      intArray0[5] = 0;
      intArray0[6] = (-229);
      intArray0[7] = 0;
      intArray0[8] = 1515;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("UJF%aU4a6.i^", intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 9
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray0 = new int[1];
      intArray0[0] = (-252);
      int[] intArray1 = new int[4];
      intArray1[0] = (-252);
      intArray1[1] = (-252);
      intArray1[2] = (-252);
      intArray1[3] = (-252);
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow(":", intArray0, intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 1386;
      int[] intArray1 = new int[4];
      intArray1[0] = 1386;
      intArray1[1] = (-1);
      intArray1[2] = 1386;
      intArray1[3] = 1386;
      SuffixArray.isSorted(intArray0, intArray1, (-1));
      String string0 = ":";
      SuffixArray.printV(intArray0, ":");
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow(":", intArray0, intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray0 = new int[9];
      intArray0[0] = 809;
      intArray0[1] = 597;
      intArray0[2] = 0;
      intArray0[3] = 2363;
      intArray0[4] = (-630);
      intArray0[5] = (-1585);
      intArray0[6] = (-5640);
      intArray0[7] = 0;
      intArray0[8] = 0;
      SuffixArray.printV(intArray0, "");
      // Undeclared exception!
      try { 
        SuffixArray.computeLCP((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SuffixArray.computeLCP("N", ";,2Wb3-T^DZl");
      int[] intArray0 = null;
      SuffixArray.isSorted((int[]) null, (int[]) null, 0);
      int int0 = 0;
      // Undeclared exception!
      try { 
        SuffixArray.sleq((int[]) null, 0, (int[]) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      intArray0[1] = 690;
      intArray0[2] = 0;
      SuffixArray.printV(intArray0, "C\"@=db\"zjK");
      int[] intArray1 = new int[4];
      intArray1[0] = 0;
      intArray1[1] = 0;
      intArray1[2] = 690;
      intArray1[3] = 690;
      SuffixArray.sleq(intArray1, 0, intArray0, 0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 1;
      // Undeclared exception!
      try { 
        SuffixArray.makeSuffixArray(intArray0, intArray0, 1, (-739));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int[] intArray0 = null;
      int int0 = 2821;
      // Undeclared exception!
      try { 
        SuffixArray.isPermutation((int[]) null, 2821);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = "net.mooctest.SuffixArray";
      int[] intArray0 = new int[2];
      int int0 = 3714;
      intArray0[0] = 3714;
      int int1 = 3381;
      intArray0[1] = 3381;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("net.mooctest.SuffixArray", intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("lah8t%)}W=se=&,`z", (int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int[] intArray0 = new int[0];
      int int0 = 0;
      SuffixArray.isPermutation(intArray0, 0);
      int int1 = (-3230);
      SuffixArray.isSorted(intArray0, intArray0, (-3230));
      String string0 = "";
      SuffixArray.createSuffixArray("", intArray0, intArray0);
      SuffixArray suffixArray0 = new SuffixArray();
      SuffixArray.printV(intArray0, "");
      // Undeclared exception!
      try { 
        SuffixArray.makeSuffixArray(intArray0, intArray0, (-1170), (-3230));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = 1418;
      intArray0[1] = (-2590);
      intArray0[2] = 0;
      SuffixArray.isSorted(intArray0, intArray0, 0);
      String string0 = "y%";
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("y%", intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = 1;
      intArray0[1] = 0;
      intArray0[2] = (-465);
      intArray0[3] = (-2523);
      intArray0[4] = 256;
      intArray0[5] = 619;
      intArray0[6] = (-1);
      // Undeclared exception!
      try { 
        SuffixArray.isPermutation(intArray0, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SuffixArray.computeLCP("", "");
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray0 = new int[7];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 0;
      intArray0[5] = 0;
      intArray0[6] = 0;
      SuffixArray.printV(intArray0, "J]56TxJx h=e(YWD");
      int[] intArray1 = new int[0];
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow("", intArray1, intArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = 256;
      intArray0[1] = 2;
      intArray0[2] = 0;
      // Undeclared exception!
      try { 
        SuffixArray.isPermutation(intArray0, 554);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[0] = 56;
      intArray0[1] = (-1);
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 3521;
      SuffixArray.createSuffixArraySlow("hH>_P", intArray0, intArray0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray0 = new int[5];
      intArray0[0] = (-2428);
      intArray0[1] = (-1);
      intArray0[2] = 1;
      intArray0[3] = (-1);
      intArray0[4] = 0;
      int[] intArray1 = new int[1];
      intArray1[0] = 256;
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray(intArray0, intArray1, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 256
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray((int[]) null, (int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      int[] intArray0 = new int[0];
      SuffixArray.printV(intArray0, "X^V)hCBjIr;'%");
      SuffixArray.makeSuffixArray(intArray0, intArray0, 0, 0);
      SuffixArray.isPermutation(intArray0, 0);
      SuffixArray.computeLCP("X^V)hCBjIr;'%", "MDnRZrr!.LOqY:WC|");
      SuffixArray.computeLCP("", "");
      SuffixArray.computeLCP("", "");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SuffixArray.computeLCP("ib", "ib");
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("ib", (int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = (-3103);
      SuffixArray.isSorted(intArray0, intArray0, (-566));
      SuffixArray.computeLCP("8noNq", "8noNq");
      SuffixArray.isSorted(intArray0, intArray0, 0);
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("", intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -3103
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      int[] intArray0 = new int[3];
      int int0 = (-1103);
      intArray0[0] = (-1103);
      intArray0[1] = (-239);
      int int1 = 1;
      intArray0[2] = 1;
      SuffixArray.isSorted(intArray0, intArray0, 1);
      SuffixArray suffixArray0 = new SuffixArray();
      String string0 = "";
      SuffixArray.printV(intArray0, "");
      String string1 = "";
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow("", intArray0, intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SuffixArray suffixArray0 = new SuffixArray();
      SuffixArray.computeLCP(" ", ":");
      int[] intArray0 = new int[7];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 0;
      intArray0[5] = 0;
      intArray0[6] = 0;
      // Undeclared exception!
      try { 
        SuffixArray.isSorted(intArray0, intArray0, 664);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int[] intArray0 = new int[1];
      int int0 = 2157;
      intArray0[0] = 2157;
      int int1 = (-1314);
      // Undeclared exception!
      try { 
        SuffixArray.isPermutation(intArray0, (-1314));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = 1;
      intArray0[1] = 0;
      intArray0[2] = (-1697);
      // Undeclared exception!
      try { 
        SuffixArray.sleq(intArray0, 0, intArray0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      int[] intArray0 = new int[5];
      int int0 = 1942;
      intArray0[0] = 1942;
      int int1 = 1;
      intArray0[1] = 1;
      intArray0[2] = 698;
      int int2 = 111;
      intArray0[3] = 111;
      int int3 = 0;
      intArray0[4] = 0;
      SuffixArray.printV(intArray0, ".");
      // Undeclared exception!
      try { 
        SuffixArray.sleq(intArray0, 1942, intArray0, 2113);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1942
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = 0;
      intArray0[1] = 231;
      intArray0[2] = 0;
      intArray0[3] = 2587;
      intArray0[4] = (-2267);
      intArray0[5] = 0;
      intArray0[6] = 0;
      // Undeclared exception!
      try { 
        SuffixArray.makeSuffixArray(intArray0, intArray0, 2, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2588
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      int int0 = (-565);
      intArray0[1] = (-565);
      intArray0[2] = 0;
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray(intArray0, intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int[] intArray0 = new int[6];
      int int0 = 3207;
      intArray0[0] = 3207;
      int int1 = 0;
      intArray0[1] = 0;
      int int2 = 0;
      intArray0[2] = 0;
      int int3 = 1;
      intArray0[3] = 1;
      int int4 = 1;
      intArray0[4] = 1;
      intArray0[5] = 0;
      SuffixArray.isSorted(intArray0, intArray0, 0);
      SuffixArray.printV(intArray0, "M");
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("", intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 6
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      int[] intArray0 = new int[0];
      SuffixArray.printV(intArray0, "");
      int int0 = (-2964);
      // Undeclared exception!
      try { 
        SuffixArray.makeSuffixArray(intArray0, intArray0, (-2964), (-2964));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[0] = 0;
      intArray0[1] = (-920);
      intArray0[2] = (-300);
      intArray0[3] = 0;
      intArray0[4] = 3;
      intArray0[5] = 2;
      intArray0[6] = (-1);
      intArray0[7] = 2332;
      intArray0[8] = 3977;
      int[] intArray1 = new int[2];
      intArray1[0] = (-1);
      intArray1[1] = 3;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow("", intArray0, intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        SuffixArray.printV((int[]) null, "edD");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String string0 = ";@MEb/Z`}eD14P";
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow(";@MEb/Z`}eD14P", (int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      intArray0[1] = 3835;
      intArray0[2] = (-593);
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray(intArray0, intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      int[] intArray0 = null;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("", (int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray0 = new int[1];
      intArray0[0] = 256;
      SuffixArray.printV(intArray0, "");
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = (-634);
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow("%u5ka{WEW/ovlrw{x", intArray0, intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      int[] intArray0 = new int[0];
      SuffixArray.printV(intArray0, "");
      // Undeclared exception!
      try { 
        SuffixArray.sleq(intArray0, (-1854), intArray0, (-1854));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1854
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      SuffixArray.computeLCP("", "h,)v!iG;Sh tA");
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow("", (int[]) null, (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      String string0 = "net.moctest.SuffixAray";
      int[] intArray0 = new int[2];
      int int0 = 3381;
      intArray0[0] = 3381;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("net.moctest.SuffixAray", intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      String string0 = "QrvH.9i_axx6\\f6";
      SuffixArray.computeLCP("QrvH.9i_axx6\f6", "");
      int[] intArray0 = new int[8];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 0;
      intArray0[5] = 0;
      intArray0[6] = 0;
      intArray0[7] = 2069;
      // Undeclared exception!
      try { 
        SuffixArray.makeSuffixArray(intArray0, intArray0, 2069, (-3840));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      String string0 = "";
      int[] intArray0 = new int[2];
      int int0 = 1;
      intArray0[0] = 1;
      intArray0[1] = 0;
      SuffixArray.createSuffixArray("", intArray0, intArray0);
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray(intArray0, intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      String string0 = "4|1";
      SuffixArray.computeLCP(" ", "4|1");
      int[] intArray0 = new int[2];
      intArray0[0] = 0;
      intArray0[1] = 0;
      SuffixArray.printV(intArray0, "4|1");
      SuffixArray.printV(intArray0, " ");
      SuffixArray.printV(intArray0, " ");
      String string1 = "";
      SuffixArray.computeLCP("", "4|1");
      // Undeclared exception!
      try { 
        SuffixArray.isSorted(intArray0, intArray0, 1568);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      int[] intArray0 = new int[3];
      int int0 = 256;
      intArray0[0] = 256;
      int int1 = 0;
      intArray0[2] = 0;
      int int2 = 554;
      // Undeclared exception!
      try { 
        SuffixArray.isPermutation(intArray0, 554);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      int[] intArray0 = new int[6];
      intArray0[0] = 531;
      intArray0[1] = 0;
      int int0 = (-1498);
      intArray0[2] = (-1498);
      int int1 = 1;
      intArray0[3] = 1;
      int int2 = 1;
      intArray0[4] = 1;
      int int3 = 0;
      intArray0[5] = 0;
      SuffixArray.isPermutation(intArray0, 0);
      SuffixArray.computeLCP("", "");
      int int4 = 0;
      SuffixArray.isSorted(intArray0, intArray0, 0);
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("xs-`sG>g`}3op", intArray0, (int[]) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 6
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[0] = 0;
      intArray0[1] = (-924);
      intArray0[2] = 560;
      intArray0[3] = 0;
      intArray0[4] = 0;
      intArray0[5] = 0;
      intArray0[6] = 3626;
      intArray0[7] = 0;
      intArray0[8] = 0;
      SuffixArray.isPermutation(intArray0, 0);
      SuffixArray suffixArray0 = new SuffixArray();
      int[] intArray1 = new int[2];
      intArray1[0] = (-1);
      SuffixArray.printV(intArray1, "");
      intArray1[1] = 560;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArraySlow("", intArray1, intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 0;
      int[] intArray1 = new int[28];
      intArray1[0] = 0;
      intArray1[1] = 0;
      intArray1[2] = 0;
      intArray1[3] = 0;
      intArray1[4] = 0;
      intArray1[5] = 0;
      intArray1[6] = 0;
      intArray1[7] = 0;
      intArray1[8] = 0;
      SuffixArray.isSorted(intArray0, intArray1, 0);
      SuffixArray.printV(intArray1, "X");
      SuffixArray.computeLCP("X", "X");
      int[] intArray2 = new int[1];
      intArray2[0] = 1;
      SuffixArray.sleq(intArray0, 0, intArray2, 0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      int[] intArray0 = new int[2];
      SuffixArray.createSuffixArray("eU", intArray0, intArray0);
      SuffixArray.isSorted(intArray0, intArray0, 0);
      // Undeclared exception!
      try { 
        SuffixArray.makeLCPArray(intArray0, intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      String string0 = "net.mooctest.SuffixArray";
      int[] intArray0 = new int[2];
      int int0 = 3714;
      intArray0[0] = 3714;
      int int1 = 256;
      intArray0[1] = 256;
      // Undeclared exception!
      try { 
        SuffixArray.createSuffixArray("net.mooctest.SuffixArray", intArray0, intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      int[] intArray0 = new int[1];
      int int0 = 2431;
      intArray0[0] = 2431;
      // Undeclared exception!
      try { 
        SuffixArray.isSorted(intArray0, intArray0, 2431);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      int[] intArray0 = new int[2];
      int int0 = (-2927);
      intArray0[0] = (-2927);
      intArray0[1] = (-308);
      SuffixArray.createSuffixArraySlow("M=", intArray0, intArray0);
      // Undeclared exception!
      try { 
        SuffixArray.computeLCP((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         // verifyException("net.mooctest.SuffixArray", e);
      }
  }
}
