/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 25 01:15:53 GMT 2018
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;
import net.mooctest.JCLO;
import org.junit.runner.RunWith;

public class JCLO_ESTest{

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object object0 = new Object();
      String[][] stringArray0 = new String[8][7];
      String[] stringArray1 = new String[7];
      stringArray1[0] = "--";
      stringArray0[0] = stringArray1;
      stringArray0[1] = stringArray1;
      stringArray0[2] = stringArray1;
      stringArray0[3] = stringArray0[0];
      stringArray0[4] = stringArray0[0];
      String[] stringArray2 = new String[0];
      stringArray0[5] = stringArray2;
      JCLO jCLO0 = new JCLO(object0, stringArray0);
      // Undeclared exception!
      try { 
        jCLO0.parse(stringArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
          assertEquals("0",e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[][] stringArray0 = new String[4][5];
      JCLO jCLO0 = null;
      try {
        jCLO0 = new JCLO((String) null, (Object) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
        assertNull(e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JCLO jCLO0 = null;
      try {
        jCLO0 = new JCLO((String) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
          assertNull(e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[][] stringArray0 = new String[0][9];
      JCLO jCLO0 = null;
      try {
        jCLO0 = new JCLO((Object) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
          assertNull(e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JCLO jCLO0 = null;
      try {
        jCLO0 = new JCLO((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
          assertNull(e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JCLO jCLO0 = new JCLO("");
      String[] stringArray0 = new String[0];
      jCLO0.parse(stringArray0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Object object0 = new Object();
      String[][] stringArray0 = new String[2][0];
      String[] stringArray1 = new String[6];
      stringArray1[0] = "";
      stringArray0[0] = stringArray1;
      String[] stringArray2 = new String[5];
      stringArray2[0] = "--";
      stringArray0[1] = stringArray2;
      JCLO jCLO0 = new JCLO(object0, stringArray0);
      // Undeclared exception!
      try { 
        jCLO0.parse(stringArray2);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No such option: \"null\"
         //
          assertEquals("No such option: \"null\"",e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Object object0 = new Object();
      String[][] stringArray0 = new String[9][1];
      String[] stringArray1 = new String[7];
      stringArray1[0] = "-' requir6es '=VALU'";
      JCLO jCLO0 = new JCLO("s}{LQ@RbY\",bVvalue", object0, stringArray0);
      // Undeclared exception!
      try { 
        jCLO0.parse(stringArray1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JCLO jCLO0 = new JCLO("~\"!vbvJhLq[@:(~");
      String[] stringArray0 = new String[9];
      stringArray0[0] = "-hash int\n";
      // Undeclared exception!
      try { 
        jCLO0.parse(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No such option: \"ash int
         // \"
         //
          assertEquals("No such option: \"hash int\n\"",e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JCLO jCLO0 = new JCLO("E", "E");
      String string0 = jCLO0.usage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[][] stringArray0 = new String[9][9];
      JCLO jCLO0 = new JCLO("", "", stringArray0);
      String string0 = jCLO0.usage();
      assertEquals("-hash int\n", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JCLO jCLO0 = new JCLO("~\"!vbvJhLq[@:(~");
      String string0 = jCLO0.usage();
      assertEquals("-hash int\n", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Object object0 = new Object();
      JCLO jCLO0 = new JCLO(object0);
      String string0 = jCLO0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Object object0 = new Object();
      String[][] stringArray0 = new String[9][1];
      String[] stringArray1 = new String[7];
      stringArray1[0] = "s}{LQ@RbY\",bVvalue";
      JCLO jCLO0 = new JCLO("s}{LQ@RbY\",bVvalue", object0, stringArray0);
      jCLO0.parse(stringArray1);
      assertEquals(7, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JCLO jCLO0 = new JCLO("", "");
      // Undeclared exception!
      try { 
        jCLO0.toString();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // [C cannot be cast to [Ljava.lang.Object;
         //
          assertEquals("[C cannot be cast to [Ljava.lang.Object;",e.getMessage());
         //verifyException("net.mooctest.JCLO", e);
      }
  }
    
}
